USE [DWCOOPAC]
GO
/****** Object:  StoredProcedure [dbo].[usp_dwt_reporte6]    Script Date: 04/04/2024 16:45:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER procedure [dbo].[usp_dwt_actualizar_dinerofresco]
as


INSERT INTO ST_BITACORA_CAMBIOS_DINERO_FRESCO  (CODCIPPERSONA, FECHAAPERTURA, MONTOAPERTURA,DF,DF_ACTUALIZADO,DNF,DNF_ACTUALIZADO,DF_CONS,DF_CONS_ACTUALIZADO,DNF_CONS,DNF_CONS_ACTUALIZADO,FECHA_PROCESO,FECHA_ACTUALIZACION)
SELECT 
	D.CODCIPPERSONA,
	D.FECHAAPERTURA,
	D.MONTOAPERTURA, 
	D.DF,
	DD.DF[DF_ACTUALIZADO],
	D.DNF,
	DD.DNF[DNF_ACTUALIZADO],
	D.DF_CONS,
	DD.DF_CONS[DF_CONS_ACTUALIZADO],
	D.DNF_CONS,
	DD.DNF_CONS[DNF_CONS_ACTUALIZADO],
	D.FECHA_PROCESO,
	FECHA_ACTUALIZACION=GETDATE()
--INTO ST_BITACORA_CAMBIOS_DINERO_FRESCO
FROM 
	WT_DINERO_FRESCO_DPF D
INNER JOIN 
	WT_DINERO_FRESCO_DPF_CONSOLIDADO DD 
	ON D.codcippersona=DD.codcippersona AND D.numerocuenta=DD.numerocuenta AND D.fechaapertura=DD.fechaapertura
	WHERE DD.DIFERENCIA<>0



UPDATE D
SET DF=DD.DF,
	DNF=DD.DNF,
	DF_CONS=DD.DF_CONS,
	DNF_CONS=DD.DNF_CONS,
	FECHA_PROCESO=GETDATE()
--SELECT D.DF,DD.DF,D.DNF,DD.DNF,D.DF_CONS,DD.DF_CONS,DD.DNF_CONS,DD.DF_CONS 
FROM 
	WT_DINERO_FRESCO_DPF D
INNER JOIN 
	WT_DINERO_FRESCO_DPF_CONSOLIDADO DD 
	ON D.codcippersona=DD.codcippersona AND D.numerocuenta=DD.numerocuenta AND D.fechaapertura=DD.fechaapertura
	WHERE DD.DIFERENCIA<>0

