USE [DWCOOPAC]
-- Definición de las fechas
	DECLARE @FECHA DATE = (SELECT fecha FROM ST_FECHAMAESTRA WHERE estado = 1);


-- Calendario de cierres y mes actual completo - se usa para el tipo de cambio mensual
	DROP TABLE IF EXISTS #CALENDARIO;
	SELECT DISTINCT Fecha 
	INTO #CALENDARIO
	FROM dimtiempo 
	WHERE (DiaNegativo = -1 AND fecha <= @fecha) 
	   OR (fecha BETWEEN DATEADD(dd, 1, EOMONTH(CAST(@fecha AS DATE), -1)) AND @fecha);


-- Calendario este año - se usa para la tabla final, limita el tiempo que figurara, a solicitud de gloria solo 2023 en adelante
	DROP TABLE IF EXISTS #CALENDARIOHISYEAR;
	SELECT DISTINCT fecha 
	INTO #CALENDARIOHISYEAR
	FROM dimtiempo 
	WHERE fecha BETWEEN DATEFROMPARTS(YEAR(GETDATE() - 1), 1, 1) AND CAST(GETDATE() - 1 AS DATE);


-- Aperturas	
    DROP TABLE IF EXISTS #APERTURAS	
	SELECT
	  FECHA=FECHAAPERTURA
	, NUMEROCUENTA
	, PRODUCTO
	, MONEDA
	, AGENCIA
	, PLAZODIAS
	, CANAL
	, MONTOINICIAL=MONTOINICIAL_SOLES
	INTO #APERTURAS
	FROM TEMP_DPF_MARKETING
	WHERE FLAG_APERTURA=1 AND FECHAAPERTURA>='2022-12-31'


-- Cancelaciones	
    DROP TABLE IF EXISTS #CANCELACIONES	
	SELECT
	  FECHA=FECHAAPERTURA
	, NUMEROCUENTA
	, PRODUCTO
	, MONEDA
	, AGENCIA
	, PLAZODIAS
	, CANAL
	, IMPORTECANCELADO=IMPORTECANCELADO
	INTO #CANCELACIONES
	FROM TEMP_DPF_MARKETING
	WHERE FLAG_CANCELACION=1 AND FECHAAPERTURA>='2022-12-31'
