USE DWCOOPAC
DROP TABLE IF EXISTS TEMP_CUENTA_MOVIMIENTO
SELECT TOP 20
  NUMEROCUENTA
, FECHAMOVIMIENTO
, IMPORTE1
INTO TEMP_CUENTA_MOVIMIENTO
FROM [dbo].[DW_CUENTAMOVIMIENTO] NOLOCK
WHERE dw_fechaCarga='2023-12-04'



SELECT  * FROM TEMP_CUENTA_MOVIMIENTO

SELECT distinct dw_fechaCarga, FECHAMOVIMIENTO FROM TEMP_CUENTA_MOVIMIENTO