USE [DWCOOPAC]
----RENTABILIDAD
-- DESEMBOLSOS 

SELECT TOP 10 * FROM DW_PRESTAMOANEXO


SELECT TOP 10 FECHADESEMBOLSO, * FROM DW_PRESTAMO


SELECT TOP 10  * FROM DW_PRESTAMO
SELECT TOP 10  * FROM DW_SOLICITUDPRESTAMO

---TASA DE PRESTAMO


drop table if exists #
SELECT DISTINCT
SP.CodigoSolicitud,
SP.FechaSolicitud,
P.FechaDesembolso,
SP.TASAADICIONAL,
FlgOperacion=1,
FlgDesembolso=IIF(P.FECHADESEMBOLSO IS NOT NULL,1,0)
FROM  DW_SOLICITUDPRESTAMO SP
LEFT JOIN DW_PRESTAMO P
ON SP.CODIGOSOLICITUD=P.CODIGOSOLICITUD
where 
SP.DW_FECHACARGA='2023-11-13' AND
SP.FECHASOLICITUD>='2023-01-01' AND P.FECHADESEMBOLSO IS NOT NULL


SELECT * FROM temp_indicadores_diarios
SELECT * FROM DW_SOLICITUDPRESTAMO

----tasa original del crédito


