-- Utilizar la base de datos DWCOOPAC
USE [DWCOOPAC];

-- Declarar la fecha de la tabla FECHAMAESTRA
DECLARE @FECHAFIN DATE;
SET @FECHAFIN = (SELECT FECHA FROM [DWCOOPAC].dbo.FECHAMAESTRA);

--DROP TABLE IF EXISTS FECHAMAESTRA
--SELECT DATEADD(DAY, -1, FECHA )FECHA
--INTO FECHAMAESTRA
--FROM [DWCOOPAC].dbo.ST_FECHAMAESTRA

DECLARE @FECHAINICIO DATE;
SET @FECHAINICIO = (SELECT DATEADD(DAY, -7, FECHA )FROM [DWCOOPAC].dbo.FECHAMAESTRA);



---déposito en doláres $ 500  , plazo fijo S/.15 000 ----MONEDA CRUZADA

--------APERTURAS-----------------------------------------------------------------------------
      DROP TABLE IF EXISTS #PASIVAS
      SELECT CODIGOSOCIO
	  , NROCUENTA
	  , MONEDA
	  , FECHAAPERTURA
	  , MONTOINICIAL
	  , MONTOINICIAL_SOLES
	  INTO #PASIVAS
      FROM DWCOOPAC.dbo.WT_REPORTEPASIVAS
      WHERE FECHA = @FECHAFIN
      AND ESTADO ='Activa' AND (TIPOPRODUCTO = 'Plazo Fijo' )
      AND FECHAAPERTURA>=@FECHAINICIO



 --------DATOS CUENTA CORRIENTE-----------------------------------------------------------------------------
	  DROP TABLE IF EXISTS #DATOSCUENTACORRIENTE
	  SELECT 
	    NUMEROCUENTA
	  , FECHAINICIO
      INTO #DATOSCUENTACORRIENTE
      FROM DW_DATOSCUENTACORRIENTE a
      WHERE NUMEROCUENTA IN (SELECT DISTINCT NROCUENTA FROM #PASIVAS)
      AND A.dw_fechacarga = @FECHAFIN--'2023-07-19' 
	  AND A.FECHAINICIO>=@FECHAINICIO



 --------OBTENIENDO MONTOS DE APERTURA------------------------------------------------------------------------
	  DROP TABLE IF EXISTS #APERTURAS_DETALLE
	  SELECT 
	    P.CODIGOSOCIO
	  , P.NROCUENTA
	  , P.MONEDA
	  , P.FECHAAPERTURA
	  , MONTOINICIAL= CASE WHEN (ROW_NUMBER() OVER(PARTITION BY NUMEROCUENTA ORDER BY FECHAINICIO ASC))=1 THEN MONTOINICIAL ELSE 0 END
	  , MONTOINICIAL_SOLES= CASE WHEN (ROW_NUMBER() OVER(PARTITION BY NUMEROCUENTA ORDER BY FECHAINICIO ASC))=1 THEN MONTOINICIAL_SOLES ELSE 0 END
	  INTO #APERTURAS_DETALLE
	  FROM #PASIVAS P
	  LEFT JOIN #DATOSCUENTACORRIENTE DCC	
	  ON P.NROCUENTA=DCC.NUMEROCUENTA 



 --------APERTURAS POR SOCIO Y MONEDA--------------------------------------------------------------------------
      DROP TABLE IF EXISTS #APERTURAS
	  SELECT 
	    CODIGOSOCIO
	  , UPPER(LEFT(MONEDA,1)) MONEDA
	  , FECHAAPERTURA
	  , SUM(MONTOINICIAL)MONTOAPERTURA 
	  , SUM(MONTOINICIAL)MONTOAPERTURA_SOLES 
	  INTO #APERTURAS
	  FROM #APERTURAS_DETALLE
	  GROUP BY CODIGOSOCIO, UPPER(LEFT(MONEDA,1)), FECHAAPERTURA

	  	  

---------REPORTE DINERO FRESCO-----------------------------------------------------------------------------
	DROP TABLE IF EXISTS #REPORTEMOVIMIENTOSDINEROFRESCO;
	SELECT
		per.CIP AS CodSocio,
		per.NOMBRECOMPLETO AS NombreCompleto,
		UPPER(LEFT(cc.MONEDADESCRI,1)) Moneda,
		a.NumeroCuenta,
		CASE 
			WHEN  a.tipomovimiento IN (1, 3, 5, 7) THEN a.importe1 
			WHEN  a.tipomovimiento IN (2, 4, 6, 8) THEN a.importe1 *-1 END AS Importe,
		a.PeriodoCaja,
		a.NumeroCaja,
		a.Observacion,
		s90.TBLDESCRI AS FormaPago,
		CASE
			WHEN a.formapago = 1 THEN 'Efectivo'
			WHEN a.formapago = 3 THEN 'Bancos'
			WHEN a.formapago = 2 THEN 'Cheque'
			WHEN a.formapago = 8 THEN 'Nota Abono'
		END AS FormaPagoFinal,
		a.FechaUsuario,
		A.CodigoUsuario,
		A.FechaMovimiento,
		CASE 
			WHEN  a.tipomovimiento IN (1, 3, 5, 7) THEN 'Ingreso'
			WHEN  a.tipomovimiento IN (2, 4, 6, 8) THEN 'Retiro' END AS Tipomovimiento
	INTO #REPORTEMOVIMIENTOSDINEROFRESCO
	FROM
		DW_CUENTAMOVIMIENTO  (NOLOCK) a
	INNER JOIN
		VW_CUENTACORRIENTE cc ON cc.numerocuenta = a.numerocuenta
	LEFT JOIN 
		DW_PERSONA (NOLOCK) per ON cc.CODIGOPERSONA = per.CODIGOPERSONA
	LEFT JOIN
		DW_SYST900 s90 (NOLOCK) ON a.FORMAPAGO = s90.TBLCODARG AND s90.TBLCODTAB = 21
	WHERE
		a.periodocaja IS NOT NULL AND 
		CAST(a.fechausuario AS DATE) BETWEEN DATEADD(DAY, -7, @FECHAINICIO) AND @FECHAFIN
		AND (
			a.observacion LIKE '%DEPOSITO EN CUENTA%'
			OR a.observacion LIKE '%REMESA KYODAI%'
			OR a.observacion LIKE '%22889%'
			OR a.observacion LIKE '%12117%'
			OR a.observacion LIKE '%Liberacion de Cheque%'
		)
		AND a.estado = 1
		AND a.tipomovimiento IN (1, 3, 5, 7, 2, 4, 6, 8)
		AND a.formapago IN (1, 2, 3, 8)
		AND cc.PRODUCTOCODIGO = 'AHV'
		AND a.codigousuario NOT IN (SELECT DISTINCT [KEY] FROM ST_TABLA_SOPORTE WHERE Comentario='Dinero fresco')
		AND a.codigoagencia NOT IN (9, 12)
		AND cc.dw_fechaCarga = @FECHAFIN
		AND per.dw_fechaCarga = @FECHAFIN;


	  
		----OBTENER MOVIMIENTOS-----------------------------------------------------------------------------
		DROP TABLE IF EXISTS #TEMP_MOVIMIENTOS
		SELECT
		  CodSocio
		, Moneda
		, FECHAMOVIMIENTO
		, SUM(Importe)MOVIMIENTO
		INTO #TEMP_MOVIMIENTOS
		FROM #REPORTEMOVIMIENTOSDINEROFRESCO WHERE FECHAMOVIMIENTO>=DATEADD(DAY, -7, @FECHAINICIO)
		GROUP BY CodSocio, Moneda, FECHAMOVIMIENTO


		DROP TABLE IF EXISTS #TEMP_MOVIMIENTOS2
	  	SELECT 
		  A.CODIGOSOCIO
		, A.FECHAAPERTURA[FECHA]
		, A.MONTOAPERTURA
		, ISNULL(M.MOVIMIENTO,0)[MOVIMIENTO]
		, M.MONEDA
		, M.FECHAMOVIMIENTO
		INTO #TEMP_MOVIMIENTOS2
		FROM #APERTURAS A
		LEFT JOIN #TEMP_MOVIMIENTOS M ON A.CODIGOSOCIO=M.CodSocio AND A.MONEDA=M.MONEDA AND A.FECHAAPERTURA>=DATEADD(DAY, -7,M.FECHAMOVIMIENTO)

		DROP TABLE IF EXISTS #MOVIMIENTOS
		SELECT CODIGOSOCIO, MONEDA ,FECHA,SUM(MOVIMIENTO)[MOVIMIENTO]
		INTO #MOVIMIENTOS
		FROM #TEMP_MOVIMIENTOS2 WHERE MONEDA IS NOT NULL
		GROUP BY CODIGOSOCIO, MONEDA ,FECHA


		----OBTENER SOCIOS CON MOVIMIENTOS EN MONEDA CRUZADA--------------------------------------------------------------   
		DROP TABLE IF EXISTS #MONEDACRUZADA
		SELECT A.CODIGOSOCIO,A.MONEDA,M.FECHA
		INTO #MONEDACRUZADA
		FROM (SELECT * FROM #APERTURAS WHERE CODIGOSOCIO IN (SELECT DISTINCT CODIGOSOCIO FROM #MOVIMIENTOS)) A 
		LEFT JOIN #MOVIMIENTOS M ON A.CODIGOSOCIO=M.CODIGOSOCIO AND A.MONEDA=M.Moneda AND A.FECHAAPERTURA=FECHA
		WHERE M.Moneda IS NULL




		----CONVERTIR MONTOS DE MOVIMIENTOS EN MONEDA CRUZADA
		DROP TABLE IF EXISTS #MOVIMIENTOS2
		SELECT M.* 
		, MONEDA2=ISNULL(MC.MONEDA,M.Moneda)
		, MOVIMIENTO2=CASE WHEN MC.MONEDA IS NULL THEN M.MOVIMIENTO 
						   WHEN MC.MONEDA='D' THEN M.MOVIMIENTO/3.875 
						   WHEN MC.MONEDA='S' THEN M.MOVIMIENTO*3.875 END
        INTO #MOVIMIENTOS2
		FROM #MOVIMIENTOS M
		LEFT JOIN #MONEDACRUZADA MC ON M.CODIGOSOCIO=MC.CODIGOSOCIO AND M.FECHA=MC.FECHA



-------DINERO FRESO DEL MISMO DIA CON EL MISMO TIPO DE MONEDA
		SELECT 
		  A.CODIGOSOCIO
		, A.MONEDA
		, A.FECHAAPERTURA[FECHA]
		, A.MONTOAPERTURA
		---, ISNULL(M.MOVIMIENTO,0)[MOVIMIENTO_INICIAL]
		, ISNULL(M.MOVIMIENTO2,0)[MOVIMIENTO]
		, DINEROFRESCO= CASE WHEN ISNULL(M.MOVIMIENTO2,0)>=A.MONTOAPERTURA THEN A.MONTOAPERTURA
		                     WHEN A.MONTOAPERTURA>ISNULL(M.MOVIMIENTO2,0)THEN ISNULL(M.MOVIMIENTO2,0) ELSE 0 END
		, DINERONOFRESCO=CASE WHEN ISNULL(M.MOVIMIENTO2,0)>=A.MONTOAPERTURA THEN 0 
		                      WHEN A.MONTOAPERTURA>ISNULL(M.MOVIMIENTO2,0)THEN A.MONTOAPERTURA-ISNULL(M.MOVIMIENTO2,0) ELSE A.MONTOAPERTURA END
	    , MONEDA_CRUZADA=IIF(MC.Moneda IS NOT NULL,'SI','NO')


		FROM #APERTURAS A
		LEFT JOIN #MOVIMIENTOS2 M ON A.CODIGOSOCIO=M.CODIGOSOCIO AND A.MONEDA=M.MONEDA2 AND A.FECHAAPERTURA>=DATEADD(DAY, -7,M.FECHA)
		LEFT JOIN #MONEDACRUZADA MC ON A.CODIGOSOCIO=MC.CODIGOSOCIO AND A.MONEDA=MC.MONEDA AND A.FECHAAPERTURA>=DATEADD(DAY, -7,M.FECHA)


		 where A.CODIGOSOCIO='1300788'

---0002090


	  select * from #PASIVAS where CODIGOSOCIO='1300788'
	  select * from #DATOSCUENTACORRIENTE where  NUMEROCUENTA IN (SELECT DISTINCT NUMEROCUENTA FROM #PASIVAS where CODIGOSOCIO='1300788' )
	  select * from #APERTURAS_DETALLE where CODIGOSOCIO='1300788'
	  select * from #APERTURAS where CODIGOSOCIO='1300788'
	  select * from #REPORTEMOVIMIENTOSDINEROFRESCO where CodSocio='1300788'
	  select * from #TEMP_MOVIMIENTOS where CodSocio='1300788'
	  select * from #TEMP_MOVIMIENTOS2 where CODIGOSOCIO='1300788'
	  select * from #MOVIMIENTOS  where CodSocio='1300788'
	  select * from #MONEDACRUZADA  where CODIGOSOCIO='1300788'
	  select * from #MOVIMIENTOS2  where CodSocio='1300788'