USE [DWCOOPAC]
GO

DECLARE @FECHA DATE = (SELECT FECHA FROM ST_FECHAMAESTRA WHERE estado = 1)

-- Creación y llenado de #DW_PERSONA
DROP TABLE IF EXISTS #DW_PERSONA
SELECT DISTINCT 
       P.CODIGOPERSONA, 
       P.CIP, 
       P.NOMBRECOMPLETO, 
       P.TIPOPERSONADESCRI, 
       P.TIPODOCUMENTOID, 
       P.NUMERODOCUMENTOID, 
       P.NUMERORUC
INTO #DW_PERSONA
FROM DW_PERSONA P WITH (NOLOCK)
WHERE P.DW_FECHACARGA = @FECHA

-- Creación y llenado de #DW_DATOSSOCIO
DROP TABLE IF EXISTS #DW_DATOSSOCIO
SELECT DISTINCT
       CODIGOPERSONA, 
       CODIGOSOCIO, 
       CODIGOAGENCIA, 
       FECHAINGRESOCOOP
INTO #DW_DATOSSOCIO
FROM DW_DATOSSOCIO WITH (NOLOCK)
WHERE DW_FECHACARGA = @FECHA

-- Creación y llenado de #TEMP_DEF_APERTURA
DROP TABLE IF EXISTS #TEMP_DEF_APERTURA
SELECT 
       p.CIP AS CODIGOSOCIO, 
       cc.NUMEROCUENTA, 
       dc.MONTOINICIAL AS [MONTO], 
       CONVERT(DATE,cc.FECHAAPERTURA) AS [FECHA]
INTO #TEMP_DEF_APERTURA
FROM DWT_CUENTACORRIENTE cc WITH (NOLOCK)
INNER JOIN #DW_PERSONA p
    ON cc.CODIGOPERSONA = p.CODIGOPERSONA
INNER JOIN DWT_DATOSCUENTACORRIENTE dc WITH (NOLOCK)
    ON dc.NUMEROCUENTA = cc.NUMEROCUENTA 
    AND dc.FECHAINICIO = CAST(cc.FECHAAPERTURA AS DATE)
INNER JOIN #DW_DATOSSOCIO dsoc 
    ON dsoc.CODIGOPERSONA = cc.CODIGOPERSONA
--WHERE cc.DW_FECHACARGA = @FECHA  AND dc.DW_FECHACARGA=@FECHA
AND cc.TABLASERVICIO=102 


DROP TABLE IF EXISTS #DEF_APERTURA
SELECT
	NOMBRE=' DPF Apertura',
	FECHA,
	MONTO
	INTO #DEF_APERTURA
FROM #TEMP_DEF_APERTURA
GROUP BY FECHA, MONTO
