 --=================================================================================================================================================================================================
    DECLARE @FECHA DATE = (SELECT FECHA FROM ST_FECHAMAESTRA WHERE ESTADO = 1)

	DROP TABLE IF EXISTS WT_REPORTEPASIVAS_DPF
	SELECT *,
	FECHA_CANCELACION=IIF(FECHACANCELACION='-',NULL, FECHACANCELACION),
	ORDENPLAZODIAS_O = CASE
                            WHEN PLAZODIAS = '30' THEN 1
                            WHEN PLAZODIAS = '60' THEN 2
                            WHEN PLAZODIAS = '90' THEN 3
                            WHEN PLAZODIAS = '180' THEN 4
                            WHEN PLAZODIAS = '360' THEN 5
                            WHEN PLAZODIAS = '720' THEN 6
                            WHEN PLAZODIAS = '1080' THEN 7
                            WHEN PLAZODIAS = '1800' THEN 8	
                            WHEN PLAZODIAS = '3600' THEN 9
                            WHEN PLAZODIAS = '5400' THEN 10
                            ELSE 11 END,
	MONEDA2= IIF(MONEDA='Soles','S','D'),
	AÑO_APERTURA=YEAR(FECHAAPERTURA),
	AÑO_CANCELACION=YEAR(IIF(FECHACANCELACION='-',NULL, FECHACANCELACION)),
	AÑO_VENCIMIENTO=YEAR(FECHAVENCIMIENTO),
	VARIACION=MONTOINICIAL_SOLES-SALDO_SOLES,
	VARIACION2=SALDO_SOLES-MONTOINICIAL_SOLES,
	VARIACION3= MONTOINICIAL_SOLES-IMPORTECANCELADO_SOLES,
	FECHAACTUALIZACION=@FECHA
	INTO WT_REPORTEPASIVAS_DPF
	FROM WT_REPORTEPASIVAS NOLOCK
	WHERE ESTADO IN ('Activa','Liquidada') AND TIPOPRODUCTO='Plazo Fijo'
	and FECHA=@FECHA

	--SELECT * FROM WT_REPORTEPASIVAS_DPF

	DELETE FROM WT_REPORTEPASIVAS_RESUMEN WHERE FECHA=@FECHA
	INSERT INTO WT_REPORTEPASIVAS_RESUMEN
	SELECT 
	PERIODO,
	FECHA,
	TIPOCAMBIO,
	AGENCIAAPERTURA,
	PERSONERIA,
	TIPOPRODUCTO,
	PLAZODIAS,
	MONEDA,
	COUNT(DISTINCT CODIGOSOCIO)SOCIOS,
	COUNT(DISTINCT NROCUENTA)CUENTAS,
	SUM(SALDO_SOLES)SALDO,
	FECHAACTUALIZACION=@FECHA
	--INTO WT_REPORTEPASIVAS_RESUMEN
	FROM WT_REPORTEPASIVAS NOLOCK
	WHERE ESTADO IN ('Activa','Liquidada') AND FECHA=@FECHA
	GROUP BY PERIODO,FECHA,TIPOCAMBIO,AGENCIAAPERTURA,PERSONERIA,TIPOPRODUCTO,PLAZODIAS,MONEDA
	ORDER BY PERIODO, FECHA


