USE [DWCOOPAC]
GO
-- Declarar la fecha de la tabla FECHAMAESTRA
DECLARE @FECHA DATE;
SET @FECHA = (SELECT FECHA FROM [DWCOOPAC].dbo.ST_FECHAMAESTRA);

--DECLARE @FECHACAMPANA DATE;
--SET @FECHACAMPANA = (
--					SELECT INICIO FROM   [dbo].[ST_CAMPANAS]
--					WHERE INICIO<=CONVERT(DATE,GETDATE()) AND FIN>=CONVERT(DATE,GETDATE()));

DECLARE @TC DECIMAL(15,3) = (select promedio from DW_XTIPOCAMBIO where fecha = (select fecha from st_fechamaestra where estado = 1) and codigoTipoCambio = 3)

---------------------Extraer movimientos del reporte 6------------------------------------------------------------
DROP TABLE IF EXISTS #REPORTE6
SELECT 
	CODIGO,
	MONEDA,
	DINERO_FRESCO,
	FECHAUSUARIO,
	MAX(HORA)HORA,
	STRING_AGG(FORMAPAGO2, ', ') AS FORMAPAGO2,
	NFORMAPAGO=IIF(FORMAPAGO2='Transf. Interna',2,1),
	IMPORTE = SUM(IMPORTE)
	
INTO #REPORTE6
FROM
	WT_REPORTE6
WHERE YEAR(FECHAUSUARIO)=YEAR(@FECHA)
	AND TIPOMOVIMIENTO='ENTRADA'
	AND PRODUCTO='AHV'
GROUP BY 	CODIGO,
	NOMBRECOMPLETO,
	MONEDA,
	DINERO_FRESCO,
	FECHAUSUARIO,
	IIF(FORMAPAGO2='Transf. Interna',2,1)



---------------------Extraer movimientos del reporte 9------------------------------------------------------------	
DROP TABLE IF EXISTS #REPORTE9
SELECT *,
SOCIO_UNICO=IIF(ROW_NUMBER() OVER(PARTITION BY CODCIPPERSONA,FECHAAPERTURA,MONEDA
			ORDER BY FECHAAPERTURA)>1,0,1)
			                         
INTO #REPORTE9
FROM 
	WT_REPORTE9
WHERE YEAR(FECHAAPERTURA)=YEAR(@FECHA)



---------------------Añadir la forma de pago------------------------------------------------------------
DROP TABLE IF EXISTS #TREPORTE9
SELECT R9.* ,R6.FORMAPAGO2
INTO #TREPORTE9
FROM 
	#REPORTE9 R9
LEFT JOIN 
	(SELECT * FROM #REPORTE6 WHERE NFORMAPAGO=1 AND IMPORTE>0)R6
ON R9.codcippersona=R6.CODIGO AND R9.MONEDA=R6.MONEDA  AND  R9.FECHAAPERTURA=R6.FECHAUSUARIO



-------------------Agregando la columnas adicionales al reporte------------------
-----1.Dinero Fresco---------------------
DROP TABLE IF EXISTS #DINEROFRESCO
SELECT R9.*,
	MONTOAPERTURA = IIF(R9.SOCIO_UNICO=1, SUM(R9.MONTOINICIAL) OVER (PARTITION BY R9.CODCIPPERSONA ,R9.FECHAAPERTURA,R9.MONEDA ),0),
	DF1 =  IIF(R9.SOCIO_UNICO=1,ISNULL(R6.IMPORTE,0),0)
INTO #DINEROFRESCO
FROM 
	#TREPORTE9 R9 
LEFT JOIN  
	(SELECT * FROM #REPORTE6 WHERE DINERO_FRESCO='SI')R6
ON R9.codcippersona=R6.CODIGO AND R9.MONEDA=R6.MONEDA  AND  R9.FECHAAPERTURA=R6.FECHAUSUARIO AND R9.HORAAPERTURA>=R6.HORA



-----2.No Dinero Fresco Transferencia interna---------------------
DROP TABLE IF EXISTS #DINEROFRESCO2
SELECT D.*,
	TRANSFERENCIA_INTERNA =  IIF(D.SOCIO_UNICO=1,ISNULL(R6.IMPORTE,0),0)
INTO #DINEROFRESCO2
FROM 
	#DINEROFRESCO D
LEFT JOIN  
	(SELECT * FROM #REPORTE6 WHERE DINERO_FRESCO='NO')R6
ON D.codcippersona=R6.CODIGO AND D.MONEDA=R6.MONEDA  AND  D.FECHAAPERTURA=R6.FECHAUSUARIO


-----3.Obtener registros sin dinero fresco y que sus movimientos del día sean menor al monto de apertura---------------------
DROP TABLE IF EXISTS #SIN_DINERO_FRESCO
SELECT * 
INTO #SIN_DINERO_FRESCO
FROM 
	#DINEROFRESCO2
WHERE
	DF1=0 AND  TRANSFERENCIA_INTERNA<MONTOAPERTURA 


-----4. Buscar movimientos 1,2 días atrás---------------------
DROP TABLE IF EXISTS #DINEROFRESCO_1DIA;
SELECT 
    B.CODIGO,
    A.MONTOAPERTURA,
    A.fechaapertura,
    A.moneda,
    B.IMPORTE,
    B.FECHAUSUARIO
INTO #DINEROFRESCO_1DIA
FROM 
    #SIN_DINERO_FRESCO A
INNER JOIN 
    #REPORTE6 B ON A.codcippersona = B.codigo AND A.moneda = B.MONEDA
WHERE 
    B.FECHAUSUARIO = DATEADD(DAY, -1, A.FECHAAPERTURA) 
    AND A.HORAAPERTURA >= B.HORA
    AND B.DINERO_FRESCO = 'SI'


DROP TABLE IF EXISTS #DINEROFRESCO_2DIAS;
SELECT 
    B.CODIGO,
    A.MONTOAPERTURA,
    A.fechaapertura,
    A.moneda,
    B.IMPORTE,
    B.FECHAUSUARIO
INTO #DINEROFRESCO_2DIAS
FROM 
    #SIN_DINERO_FRESCO A
INNER JOIN 
    #REPORTE6 B ON A.codcippersona = B.codigo AND A.moneda = B.MONEDA
WHERE 
    B.FECHAUSUARIO <= DATEADD(DAY, -2, A.FECHAAPERTURA) 
    AND A.HORAAPERTURA >= B.HORA
    AND B.DINERO_FRESCO = 'SI'


DROP TABLE IF EXISTS #DINEROFRESCO_3DIAS;
SELECT 
    B.CODIGO,
    A.MONTOAPERTURA,
    A.fechaapertura,
    A.moneda,
    B.IMPORTE,
    B.FECHAUSUARIO
INTO #DINEROFRESCO_3DIAS
FROM 
    #SIN_DINERO_FRESCO A
INNER JOIN 
    #REPORTE6 B ON A.codcippersona = B.codigo AND A.moneda = B.MONEDA
WHERE 
    B.FECHAUSUARIO <= DATEADD(DAY, -3, A.FECHAAPERTURA) 
    AND A.HORAAPERTURA >= B.HORA
    AND B.DINERO_FRESCO = 'SI'

-----5. Buscar movimientos 7 días atrás---------------------
DROP TABLE IF EXISTS #TEMP_DINEROFRESCO_7DIAS;
SELECT 
    B.CODIGO,
    A.MONTOAPERTURA,
    A.fechaapertura,
    A.moneda,
    B.FECHAUSUARIO,
    ROW_NUMBER() OVER (PARTITION BY B.CODIGO, B.FECHAUSUARIO, A.MONEDA ORDER BY FECHAUSUARIO ASC) AS N,
	ROW_NUMBER() OVER (PARTITION BY B.CODIGO, A.FECHAAPERTURA, A.MONEDA ORDER BY FECHAUSUARIO ASC) AS N2,
    SUM(B.IMPORTE) AS IMPORTE
INTO #TEMP_DINEROFRESCO_7DIAS
FROM 
    #SIN_DINERO_FRESCO A
INNER JOIN 
    #REPORTE6 B ON A.codcippersona = B.codigo AND A.moneda = B.MONEDA
WHERE 
    B.FECHAUSUARIO BETWEEN DATEADD(DAY, -7, CAST(A.FECHAAPERTURA AS DATETIME) + CAST(A.HORAAPERTURA AS DATETIME)) 
    AND CAST(A.FECHAAPERTURA AS DATETIME) + CAST(A.HORAAPERTURA AS DATETIME)
    AND B.DINERO_FRESCO = 'SI'
GROUP BY 
    B.CODIGO, A.MONTOAPERTURA, A.fechaapertura, A.moneda, B.FECHAUSUARIO
ORDER BY 
    A.fechaapertura;


DROP TABLE IF EXISTS #ELIMINAR
SELECT * 
INTO #ELIMINAR
FROM #TEMP_DINEROFRESCO_7DIAS WHERE  N=2
UNION 
SELECT * FROM #TEMP_DINEROFRESCO_7DIAS 
WHERE CONCAT(CODIGO,FECHAUSUARIO,IMPORTE) IN (SELECT CONCAT(CODIGO,FECHAUSUARIO,IMPORTE)  FROM #TEMP_DINEROFRESCO_7DIAS WHERE  N=2 ) AND N2=2


DROP TABLE IF EXISTS #TEMP_DINEROFRESCO_7DIAS_2 
SELECT * 
INTO #TEMP_DINEROFRESCO_7DIAS_2 
FROM #TEMP_DINEROFRESCO_7DIAS 
WHERE CONCAT(CODIGO,MONTOAPERTURA,fechaapertura,moneda,FECHAUSUARIO,IMPORTE) 
NOT IN (SELECT CONCAT(CODIGO,MONTOAPERTURA,fechaapertura,moneda,FECHAUSUARIO,IMPORTE)  FROM #ELIMINAR)




DROP TABLE IF EXISTS #DINEROFRESCO_7DIAS
SELECT CODIGO, MONTOAPERTURA,FECHAAPERTURA,MONEDA,IMPORTE,FECHAUSUARIO
INTO #DINEROFRESCO_7DIAS
FROM #TEMP_DINEROFRESCO_7DIAS_2
UNION

SELECT DISTINCT A.* 
FROM #DINEROFRESCO_1DIA A INNER JOIN
(SELECT * FROM #TEMP_DINEROFRESCO_7DIAS WHERE N=2) B ON A.CODIGO=B.CODIGO AND A.fechaapertura=B.fechaapertura AND A.FECHAUSUARIO=B.FECHAUSUARIO
UNION

SELECT DISTINCT A.* 
FROM #DINEROFRESCO_2DIAS A INNER JOIN
(SELECT * FROM #TEMP_DINEROFRESCO_7DIAS WHERE N=2) B ON A.CODIGO=B.CODIGO AND A.fechaapertura=B.fechaapertura AND A.FECHAUSUARIO=B.FECHAUSUARIO
UNION

SELECT DISTINCT A.* 
FROM #DINEROFRESCO_3DIAS A INNER JOIN
(SELECT * FROM #TEMP_DINEROFRESCO_7DIAS WHERE N=2) B ON A.CODIGO=B.CODIGO AND A.fechaapertura=B.fechaapertura AND A.FECHAUSUARIO=B.FECHAUSUARIO
UNION

SELECT DISTINCT A.* 
FROM #DINEROFRESCO_2DIAS A INNER JOIN
(SELECT * FROM #TEMP_DINEROFRESCO_7DIAS WHERE N=2) B ON A.CODIGO=B.CODIGO AND A.fechaapertura=B.fechaapertura AND A.FECHAUSUARIO=B.FECHAUSUARIO




-----6.Armando reporte pre final de dinero fresco---------------------
DROP TABLE IF EXISTS #WT_DINERO_FRESCO_DPF_1
SELECT D.*,
	DF =  IIF(D.SOCIO_UNICO=1,
			CASE WHEN ISNULL(D7.IMPORTE,D.DF1) >= D.MONTOAPERTURA THEN D.MONTOAPERTURA
				 WHEN D.MONTOAPERTURA >ISNULL(D7.IMPORTE,D.DF1) THEN ISNULL(D7.IMPORTE,D.DF1) ELSE 0 END,0),
	DNF = IIF(D.SOCIO_UNICO=1, 
			CASE WHEN ISNULL(D7.IMPORTE,D.DF1) >= D.MONTOAPERTURA THEN 0
				 WHEN D.MONTOAPERTURA >ISNULL(D7.IMPORTE,D.DF1) THEN  D.MONTOAPERTURA - ISNULL(D7.IMPORTE,D.DF1) ELSE 0 END,0)
INTO #WT_DINERO_FRESCO_DPF_1
FROM #DINEROFRESCO2  D
LEFT JOIN #DINEROFRESCO_7DIAS D7 ON D.codcippersona=D7.CODIGO AND D.fechaapertura=D7.fechaapertura AND D.moneda=D7.moneda
ORDER BY D.fechaapertura ASC



-----7.Dinero Fresco consolidado en soles---------------------
DROP TABLE IF EXISTS #DINEROFRESCOSOLES
SELECT *,
	 DF_CONS= IIF(MONEDA='S',DF,DF*@TC),
	 DNF_CONS= IIF(MONEDA='S',DNF,DNF*@TC)
INTO #DINEROFRESCOSOLES
FROM 
	#WT_DINERO_FRESCO_DPF_1




-----8.Armando reporte final de dinero fresco---------------------
DROP TABLE IF EXISTS WT_DINERO_FRESCO_DPF_CONSOLIDADO
SELECT D.*,
	TICKET_PROM = IIF(D.DF_CONS>0,'SI','NO'),
	FILTRO_PLAZO = IIF(D.NUMERODIAS IN(360,720,1080),'SI','NO' ),
	--CAMPAÑA = IIF( FECHAAPERTURA>=@FECHACAMPANA  AND NUMERODIAS IN(360,720,1080),'Campaña Actual','No'),
	C.CAMPAÑA,
	AÑO = YEAR(D.FECHAAPERTURA), 
	MES = MONTH(D.FECHAAPERTURA),
	PROD_SOLES = IIF(D.SUBPRODUCTO IN ('DPF SOLES 720','DPF SOLES 360','DPF SOLES 180','DPF SOLES 90',
									'DPF CTS SOLES 720','DPF CTS SOLES 360','DPF CTS SOLES 180','DPF CTS SOLES 90',
									'DPF PACIFIJO SOLES 720','DPF PACIFIJO SOLES 360','DPF PACIFIJO SOLES 1080',
									'DPF PACIFIJO SOLES 90'),'SI','NO'),
	PROD_DOLARES = IIF(D.SUBPRODUCTO IN ('DPF DOLARES 720' ,'DPF DOLARES 360','DPF DOLARES 180','DPF DOLARES 90','DPF CTS DOLARES 720',
									 'DPF CTS DOLARES 360','DPF CTS DOLARES 180','DPF CTS DOLARES 90','DPF PACIFIJO DOLARES 720',
									 'DPF PACIFIJO DOLARES 360','DPF PACIFIJO DOLARES 180','DPF PACIFIJO DOLARES 90'),'SI','NO'),
	FILTRO_FRS_RNV = IIF(D.DF>0,'DINERO FRESCO','RENOV.'),
	FILTRO_CANAL = IIF(D.AGENCIA_APERT = 'PACINET','DIGITAL','PRESENCIAL'),
	INICIO_CAMAPAÑA= C.INICIO,
	FECHA_PROCESO= GETDATE(),
	TIPOCAMBIO= @TC,
	DIFERENCIA=(D.DF-DD.DF)
INTO WT_DINERO_FRESCO_DPF_CONSOLIDADO
FROM #DINEROFRESCOSOLES  D
LEFT JOIN  [dbo].[ST_CAMPANAS] C ON D.fechaapertura BETWEEN C.INICIO AND C.FIN
LEFT JOIN WT_DINERO_FRESCO_DPF DD ON D.codcippersona=DD.codcippersona AND D.numerocuenta=DD.numerocuenta AND D.fechaapertura=DD.fechaapertura
ORDER BY D.fechaapertura ASC








SELECT * FROM WT_DINERO_FRESCO_DPF_CONSOLIDADO WHERE fechaapertura='2024-04-01'  AND codcippersona='0002667'

AND  fechaapertura<='2024-03-31' 
and moneda='d'

ORDER BY fechaapertura ASC

SELECT * FROM WT_REPORTE6 where CODIGO='1600786' and FECHAUSUARIO>='2024-04-01'
and DINERO_FRESCO='si'