--USE [DWCOOPAC]
--GO
--/****** Object:  StoredProcedure [dbo].[usp_dasha_colaboradores]    Script Date: 14/03/2024 11:23:16 ******/
--SET ANSI_NULLS ON
--GO
--SET QUOTED_IDENTIFIER ON
--GO

--ALTER procedure [dbo].[usp_dwt_ReporteSalidas7pm]20
-- @HORA INT
--as

DECLARE @HORA INT
SET @HORA = 20

DECLARE @FECHA DATE = CONVERT(DATE, GETDATE()-1)

EXEC [dbo].[usp_dwt_ReporteCadaHora]@HORA
DECLARE @TC DECIMAL(15,3) = (select promedio from DW_XTIPOCAMBIO where fecha = (select fecha from st_fechamaestra where estado = 1) and codigoTipoCambio = 3)

---------------------Cuadro 1-----------------------------------------------------------
DROP TABLE IF EXISTS WT_REPORTE_7PM_1
SELECT 
	[Id]=1,
	[Recaudación]='Total',
	[Dólares] = SUM(CASE WHEN MONEDA = 'DOLARES' THEN TOTAL ELSE 0 END),
    [Soles] = SUM(CASE WHEN MONEDA = 'SOLES' THEN TOTAL ELSE 0 END),
	[Consolidado]=((SUM(CASE WHEN MONEDA = 'DOLARES' THEN TOTAL ELSE 0 END)))*@TC+(SUM(CASE WHEN MONEDA = 'SOLES' THEN TOTAL ELSE 0 END))
INTO WT_REPORTE_7PM_1
FROM 
	WT_REPORTE133   
WHERE 
	CONVERT(DATE,FECHA_PROCESO,103)=@FECHA
	AND CONDICION IN ('Caja', 'Desembolso')
	AND TIPOMOVIMIENTO in ('Amortizacion','Nota Abono')
	AND ESTADO_PAGO = 'ACTIVO'



DROP TABLE IF EXISTS #REPORTE6
SELECT
	CODIGO,
	MONEDA,
	DINEROFRESCO = SUM(IMPORTE)
INTO #REPORTE6
FROM 
	WT_REPORTE6
WHERE
	CONVERT(DATE, FECHAUSUARIO) = @FECHA
	AND FILTRO_DF='Dinero fresco'
GROUP BY
	CODIGO,MONEDA


DROP TABLE IF EXISTS #REPORTE9
SELECT 
	CODIGOSOCIO=codcippersona,
	MONEDA,
	MONTOINICIAL=SUM(MONTOINICIAL),
	TASAINTANUALAPERT=SUM(TASAINTANUALAPERT)
INTO #REPORTE9
FROM 
	WT_REPORTE9 WHERE CONVERT(DATE, FECHAAPERTURA)=@FECHA AND ESTADO=1
	GROUP BY codcippersona,MONEDA



DROP TABLE IF EXISTS #REPORTE6_9
SELECT R9.*,
	DINEROFRESCO=CASE WHEN ISNULL(R6.DINEROFRESCO,0)>=R9.MONTOINICIAL THEN  R9.MONTOINICIAL 
		                     WHEN R9.MONTOINICIAL > ISNULL(R6.DINEROFRESCO,0)  THEN  ISNULL(R6.DINEROFRESCO,0) ELSE 0 END,
	RENOVACION=MONTOINICIAL-
			   (CASE WHEN ISNULL(R6.DINEROFRESCO,0)>=R9.MONTOINICIAL THEN  R9.MONTOINICIAL 
		        WHEN R9.MONTOINICIAL > ISNULL(R6.DINEROFRESCO,0)  THEN  ISNULL(R6.DINEROFRESCO,0) ELSE 0 END)
INTO #REPORTE6_9
FROM 
	#REPORTE9 R9 LEFT JOIN #REPORTE6 R6 ON R9.CODIGOSOCIO = R6.CODIGO AND R9.MONEDA = R6.MONEDA

	


---------------------Cuadro 2-----------------------------------------------------------
DROP TABLE IF EXISTS WT_REPORTE_7PM_2
SELECT
    [Id]=2,
	[Depósitos a Plazo] = 'Nuevo',
	[Dólares] = SUM(CASE WHEN MONEDA = 'D' THEN DINEROFRESCO ELSE 0 END),
    [Soles] = SUM(CASE WHEN MONEDA = 'S' THEN DINEROFRESCO ELSE 0 END),
	[Consolidado]=((SUM(CASE WHEN MONEDA = 'D' THEN DINEROFRESCO ELSE 0 END)))*@TC+(SUM(CASE WHEN MONEDA = 'S' THEN DINEROFRESCO ELSE 0 END))
INTO WT_REPORTE_7PM_2
FROM 
	#REPORTE6_9 
UNION
SELECT 
    [Id]=3,
	[Texto] = 'Canc. Anticipada',
	[D] = SUM(CASE WHEN MONEDA = 'D' THEN RENOVACION ELSE 0 END),
    [S] = SUM(CASE WHEN MONEDA = 'S' THEN RENOVACION ELSE 0 END),
	[C]=((SUM(CASE WHEN MONEDA = 'D' THEN RENOVACION ELSE 0 END)))*@TC+(SUM(CASE WHEN MONEDA = 'S' THEN RENOVACION ELSE 0 END))
FROM 
	#REPORTE6_9 
UNION
SELECT 
    [Id]=4,
	[Texto] = 'Total',
	[D] = SUM(CASE WHEN MONEDA = 'D' THEN MONTOINICIAL ELSE 0 END),
    [S] = SUM(CASE WHEN MONEDA = 'S' THEN MONTOINICIAL ELSE 0 END),
	[C]=((SUM(CASE WHEN MONEDA = 'D' THEN MONTOINICIAL ELSE 0 END)))*@TC+
	               (SUM(CASE WHEN MONEDA = 'S' THEN MONTOINICIAL ELSE 0 END))
FROM 
	#REPORTE6_9
UNION
SELECT 
    [Id]=5,
	[Texto] = 'TEA PROM %',
	[D] = AVG(CASE WHEN MONEDA = 'D' THEN TASAINTANUALAPERT ELSE 0 END),
    [S] = AVG(CASE WHEN MONEDA = 'S' THEN TASAINTANUALAPERT ELSE 0 END),
	[C]=NULL
FROM 
	#REPORTE6_9




-------Calculando Totales------
DECLARE @D1 DECIMAL(10,2)
SET @D1= (SELECT SUM([Dólares]) FROM WT_REPORTE_7PM_1)

DECLARE @S1 DECIMAL(10,2)
SET @S1= (SELECT SUM([Soles]) FROM WT_REPORTE_7PM_1)

DECLARE @C1 DECIMAL(10,2)
SET @C1= (SELECT SUM([Consolidado]) FROM WT_REPORTE_7PM_1)


DECLARE @D2 DECIMAL(10,2)
SET @D2= (SELECT SUM([Dólares]) FROM WT_REPORTE_7PM_2 WHERE [Depósitos a Plazo]='Nuevo')

DECLARE @S2 DECIMAL(10,2)
SET @S2= (SELECT SUM([Soles]) FROM WT_REPORTE_7PM_2 WHERE [Depósitos a Plazo]='Nuevo')


DECLARE @C2 DECIMAL(10,2)
SET @C2= (SELECT SUM([Consolidado]) FROM WT_REPORTE_7PM_2 WHERE [Depósitos a Plazo]='Nuevo')


-------Obtener el total de salidas del reporte de cada hora------

DECLARE @D DECIMAL(10,2)
SET @D= (SELECT SUM(D) FROM WT_REPORTECADAHORA WHERE FORMAPAGO='Total')

DECLARE @S DECIMAL(10,2)
SET @S= (SELECT SUM(S) FROM WT_REPORTECADAHORA WHERE FORMAPAGO='Total')

DECLARE @C DECIMAL(10,2)
SET @C= (SELECT SUM(CONSOLIDADO) FROM WT_REPORTECADAHORA WHERE FORMAPAGO='Total')





INSERT INTO WT_REPORTE_7PM_2
SELECT 6,'',NULL,NULL,NULL

INSERT INTO WT_REPORTE_7PM_2
SELECT 7,'Total Entradas',(@D1+@D2),(@S1+@S2),(@C1+@C2)

INSERT INTO WT_REPORTE_7PM_2
SELECT 8,'',NULL,NULL,NULL

INSERT INTO WT_REPORTE_7PM_2
SELECT 9,'Neteo E/S',(@D1+@D2-@D),(@S1+@S2-@S),(@C1+@C2-@C)


SELECT * FROM WT_REPORTE_7PM_1

SELECT * FROM WT_REPORTE_7PM_2