--USE [DWCOOPAC]
--GO
--/****** Object:  StoredProcedure [dbo].[usp_dasha_colaboradores]    Script Date: 14/03/2024 11:23:16 ******/
--SET ANSI_NULLS ON
--GO
--SET QUOTED_IDENTIFIER ON
--GO

--ALTER procedure [dbo].[usp_dwt_ReporteSalidas1pm]13
-- @HORA INT
--as


DECLARE @HORA INT
SET @HORA =13---( SELECT  DATENAME(HOUR, GETDATE()) )

DECLARE @TC DECIMAL(15,3) = (select promedio from DW_XTIPOCAMBIO where fecha = (select fecha from st_fechamaestra where estado = 1) and codigoTipoCambio = 3)

-- Declarar la fecha
DECLARE @FECHA DATE;
SET @FECHA = CONVERT(DATE, GETDATE());


---------Obtener agencias-----------------------------------------------------
DROP TABLE IF EXISTS #AGENCIAS;
SELECT *
INTO #AGENCIAS
FROM(
	SELECT 
		CODIGO,
		NOMBRECOMPLETO,
		CODIGOAGENCIANOM,
		N=ROW_NUMBER() OVER (PARTITION BY CODIGO ORDER BY HORA)
	FROM 
		WT_REPORTE6
	WHERE 
		CONVERT(DATE, FECHAUSUARIO) = @FECHA
		AND RANGO_HORA <= @HORA 
		AND TIPOPERSONADESCRI = 'Persona Natural'
		AND TIPOMOVIMIENTO = 'SALIDA') A
WHERE A.N=1



-------Traer los datos necesarios del reporte 6 con los filtros necesarios-------------
DROP TABLE IF EXISTS #REPORTE6_REPORTE66;
SELECT 
	CODIGO,
    NOMBRECOMPLETO,
    S = SUM(CASE WHEN MONEDA = 'S' THEN IMPORTE ELSE 0 END),
    D = SUM(CASE WHEN MONEDA = 'D' THEN IMPORTE ELSE 0 END),
	HORA= MAX(CONVERT(INT,RANGO_HORA))
INTO #REPORTE6_REPORTE66
FROM 
    WT_REPORTE6
WHERE 
    CONVERT(DATE, FECHAUSUARIO) = @FECHA
    AND RANGO_HORA <= @HORA 
    AND TIPOPERSONADESCRI = 'Persona Natural'
    AND TIPOMOVIMIENTO = 'SALIDA'
    AND FORMAPAGO IN ('Efectivo', 'Cheque')
    AND PRODUCTO IN ('AHV', 'CDE', 'AHC', 'AHP', 'AHF', 'CDE', 'CDJ', 'CDP')
GROUP BY 
    CODIGO,NOMBRECOMPLETO

UNION ALL

-------Traer los datos necesarios del reporte 66 con los filtros necesarios-------------

SELECT 
    CODIGOSOCIO,
	NOMBRES,
    S = SUM(CASE WHEN MONEDA = 1 THEN IMPORTESOLICITUD ELSE 0 END),
    D = SUM(CASE WHEN MONEDA = 2 THEN IMPORTESOLICITUD ELSE 0 END),
	HORA= MAX(CONVERT(INT,FILTRO_HORA))

FROM 
    WT_REPORTE66
WHERE
    CONVERT(DATE, FECHASOLICITUDTRUNCADA) = @FECHA
	AND FILTRO_HORA  <= @HORA  --IN (SELECT * FROM #HORAS)
	AND DESCESTADO = 'Liquidado'
	AND PERSONERIA = 'Natural'
	GROUP BY CODIGOSOCIO,NOMBRES

	
-------Obtener el orden del socio por el importe-------------
DROP TABLE IF EXISTS WT_REPORTE_PRINCIPALES
SELECT A.*,
	NS= ROW_NUMBER() OVER (ORDER BY S DESC), 
	ND= ROW_NUMBER() OVER (ORDER BY D DESC), 
	B.CODIGOAGENCIANOM,
	NIKKEI=IIF(C.CIP IS NOT NULL,'Nikkei','No Nikkei')
INTO WT_REPORTE_PRINCIPALES 
FROM 
	#REPORTE6_REPORTE66 A
LEFT JOIN
	#AGENCIAS B
	ON A.CODIGO=B.CODIGO
LEFT JOIN 
	WT_SOCIOSNIKKEI C
	ON A.CODIGO=C.CIP


	
-------Generar el reporte de soles-------------
DROP TABLE IF EXISTS WT_REPORTE1S
SELECT DISTINCT
	NS,
	CODIGO,
	NOMBRECOMPLETO,
	S,
	CODIGOAGENCIANOM,
	HORA,
	NIKKEI,
	FECHAACTUALIZACION=@FECHA
INTO WT_REPORTE1S
FROM 
	WT_REPORTE_PRINCIPALES
WHERE NS<11 AND S>0
ORDER BY NS ASC



-------Generar el reporte de dolares-------------
DROP TABLE IF EXISTS WT_REPORTE1D
SELECT DISTINCT
	ND,
	CODIGO,
	NOMBRECOMPLETO,
	D,
	CODIGOAGENCIANOM,
	HORA,
	NIKKEI,
	FECHAACTUALIZACION=@FECHA
INTO WT_REPORTE1D
FROM 
	WT_REPORTE_PRINCIPALES
WHERE ND<11 AND D>0
ORDER BY ND ASC

-------SOLES BASE NIKEN------
DECLARE @S FLOAT
SET @S= (SELECT SUM(S) FROM WT_REPORTE1S)

DECLARE @SNIKKEI FLOAT 
SET @SNIKKEI=(SELECT SUM(S) FROM WT_REPORTE1S A INNER JOIN WT_SOCIOSNIKKEI B ON A.CODIGO=B.CIP)


INSERT INTO WT_REPORTE1S
SELECT '','','Total',@S,'','','',@FECHA

INSERT INTO WT_REPORTE1S
SELECT '','','NIKKEI',@SNIKKEI,'','','',@FECHA

INSERT INTO WT_REPORTE1S
SELECT '','','NIKKEI %',@SNIKKEI/@S,'','','',@FECHA



-------DOLARES BASE NIKEN------
DECLARE @D FLOAT
SET @D= (SELECT SUM(D) FROM WT_REPORTE1D)

DECLARE @DNIKKEI FLOAT 
SET @DNIKKEI=(SELECT SUM(D) FROM WT_REPORTE1D A INNER JOIN WT_SOCIOSNIKKEI B ON A.CODIGO=B.CIP)

INSERT INTO WT_REPORTE1D
SELECT '','','Total',@D,'','','',@FECHA

INSERT INTO WT_REPORTE1D
SELECT '','','NIKKEI',@DNIKKEI,'','','',@FECHA

INSERT INTO WT_REPORTE1D
SELECT '','','NIKKEI %',@DNIKKEI/@D,'','','',@FECHA


SELECT (SELECT COUNT(*) FROM WT_REPORTE_PRINCIPALES WHERE S>0)+(SELECT COUNT(*) FROM WT_REPORTE_PRINCIPALES WHERE D>0) 


SELECT Moneda='Principales 10',Dólares=(SELECT D FROM WT_REPORTE1D WHERE NOMBRECOMPLETO='Total'),Soles=(SELECT S FROM WT_REPORTE1S WHERE NOMBRECOMPLETO='Total')




--SELECT * FROM WT_REPORTE1D


--SELECT * FROM WT_REPORTE1S