DECLARE @FECHA DATE;
SET @FECHA = (SELECT FECHA FROM [DWCOOPAC].dbo.ST_FECHAMAESTRA)
DECLARE @tipocambio DECIMAL(12, 3) = (
    SELECT PROMEDIO 
    FROM DW_XTIPOCAMBIO WITH (NOLOCK) 
    WHERE codigoTipoCambio = 3 AND fecha = @fecha
)

-- Crear tabla temporal para SALDOPRESTAMO
DROP TABLE IF EXISTS #PRESTAMOCUOTA
SELECT A.* 
INTO #PRESTAMOCUOTA
FROM (
    SELECT CODIGOSOLICITUD, SALDOPRESTAMO,
           N = ROW_NUMBER() OVER (PARTITION BY CODIGOSOLICITUD ORDER BY FECHAVENCIMIENTO DESC),
           ESTADO
    FROM DW_PRESTAMOCUOTAS 
    WHERE ESTADO = 1
) A
WHERE A.N = 1


-- Crear tabla temporal para INGRESOSECTORISTAS
DROP TABLE IF EXISTS #INGRESOSECTORISTAS;
SELECT 
    p.CODIGOSECTORISTA, 
    p2.NOMBRECOMPLETO AS nomsectorista, 
    p2.FECHAINGRESOCOOP AS fechaingresororiginador, 
    p.CIP
INTO #INGRESOSECTORISTAS
FROM DW_PERSONA p
LEFT JOIN DW_PERSONA p2 WITH (NOLOCK) ON p2.CODIGOPERSONA = p.CODIGOSECTORISTA AND p2.DW_FECHACARGA = @fecha
WHERE 
    p.DW_FECHACARGA = @fecha
    AND p.CODIGOSECTORISTA IS NOT NULL 
    AND p.CIP IS NOT NULL;


-- Consulta principal
DROP TABLE IF EXISTS TEMP_REPORTE
SELECT 
    P.DW_CODIGOSOCIO AS CODIGOSOCIO,
    per.NOMBRECOMPLETO AS NOMBRESOCIO,
    pr.CODIGOSOLICITUD AS NROCREDITO,
    P.FECHADESEMBOLSO,
    pr.DIASATRASO,
    RANGODIASATRASO = 
        CASE 
            WHEN pr.DIASATRASO >= 1 AND pr.DIASATRASO <= 8 THEN '1-8'
            WHEN pr.DIASATRASO >= 9 AND pr.DIASATRASO <= 15 THEN '9-15'
            WHEN pr.DIASATRASO >= 16 AND pr.DIASATRASO <= 30 THEN '16-30' 
        END,
    ORDEN_RANGODIASATRASO = 
        CASE 
            WHEN pr.DIASATRASO >= 1 AND pr.DIASATRASO <= 8 THEN 1
            WHEN pr.DIASATRASO >= 9 AND pr.DIASATRASO <= 15 THEN 2
            WHEN pr.DIASATRASO >= 16 AND pr.DIASATRASO <= 30 THEN 3
        END,
    p.DW_PRODUCTO AS PRODUCTO,
    sp.MODALIDADSOLICITUDDESCRIBE AS GRUPOCREDITO,
    se.fechaingresororiginador AS FECHAINGRESOFUNCIONARIO,
    dw_funcionarioRegistrador AS FUNCIONARIOORIGINADOR,
    pc.SALDOPRESTAMO,
    SALDOPRESTAMOSOLES = IIF(p.MONEDA = 2, pc.SALDOPRESTAMO * @tipocambio, pc.SALDOPRESTAMO),
    i.DW_TIPO AS JEFATURACOMERCIAL,
    i.TBlDESCRI,-----Por confirmar
    ALERTATEMPRANA = IIF(p.FECHADESEMBOLSO BETWEEN '2023-06-01' AND '2023-08-31', 'Fallido', 'Originación')
	INTO TEMP_REPORTE
FROM DW_PRESTAMOCUOTASRESUMEN pr WITH (NOLOCK)
LEFT JOIN DW_PRESTAMO p WITH (NOLOCK) ON pr.CODIGOSOLICITUD = p.CODIGOSOLICITUD
LEFT JOIN #PRESTAMOCUOTA pc WITH (NOLOCK) ON pr.CODIGOSOLICITUD = pc.CODIGOSOLICITUD
LEFT JOIN DW_PRESTAMOANEXOHISTORICO pa WITH (NOLOCK) ON pr.CODIGOSOLICITUD = pa.CODIGOSOLICITUD
LEFT JOIN DW_PERSONA per WITH (NOLOCK) ON p.CODIGOPERSONA = per.CODIGOPERSONA
LEFT JOIN DW_syst901 i WITH (NOLOCK) ON pa.TIPOSOLICITUD = i.TBLCODARG
LEFT JOIN #INGRESOSECTORISTAS se WITH (NOLOCK) ON se.CIP = p.DW_CODIGOSOCIO
LEFT JOIN DW_SOLICITUDPRESTAMO sp WITH (NOLOCK) ON p.CODIGOSOLICITUD = sp.CODIGOSOLICITUD

WHERE 
    p.DW_PRODUCTO NOT IN ('TAN', 'PCC', 'PCH', 'PCY', 'PFI', 'PCM', 'PDD', 'PLC', 'PCL', 'DSC', 'CUO')
    AND pr.NROCUOTASATRASADAS > 0
    AND pr.DIASATRASO <= 30
    AND pr.dw_fechacarga = @FECHA
    AND p.DW_FECHACARGA = @FECHA
    AND pa.DW_FECHACARGA = @FECHA
    AND per.DW_FECHACARGA = @FECHA
	AND SP.DW_FECHACARGA = @FECHA
    AND i.TBLCODTAB = 10

-- Eliminar tablas temporales al final
DROP TABLE IF EXISTS #INGRESOSECTORISTAS;
DROP TABLE IF EXISTS #PRESTAMOCUOTA;



--SELECT 
--CODIGOSOCIO,
--RANGODIASATRASO,
--COUNT(*)[OPERACIONES],
--SUM(SALDOPRESTAMOSOLES)[SALDOPRESTAMOSOLES]
--FROM #REPORTE
----WHERE CODIGOSOCIO='0035958'
--GROUP BY CODIGOSOCIO,RANGODIASATRASO



