USE [DWCOOPAC]
GO
SELECT  DISTINCT
    P.CIP,
    P.NOMBRECOMPLETO AS NOMBRE,
    P.TIPOPERSONADESCRI,
    P.TIPOPERSONA,
    P.SEXO,
    P.EDAD,
    P.CODIGOUSUARIO AS CODIGOUSUARIOPER,
    P.ESTADOCIVILDESCRI,
    P.NUMERODOCUMENTOID,
    P.TIPODOCUMENTODESCRI,
    CONVERT(DATE,P.FECHAINGRESOCOOP) AS FECHAINGRESOCOOP,
	DS.SITUACIONDESCRI[ESTADOCIP],
	DS.SITUACIONORIGEN,
    DS.CODIGOPERSONA,
    DS.AGENCIADESCRI,
	I.TBLDESCRI[ESTADORENUNCIA],
    CONVERT(DATE, NULL) AS FECHAAPROBACIONREN,
    CONVERT(VARCHAR(15), NULL) AS USUARIORENUNCIA


FROM DW_PERSONA P WITH (NOLOCK)
LEFT JOIN DW_DATOSSOCIO DS WITH (NOLOCK) ON P.CODIGOPERSONA=DS.CODIGOPERSONA
LEFT JOIN DW_SOLICITUDRENUNCIA SR WITH (NOLOCK) ON DS.CODIGOPERSONA = SR.CODIGOPERSONA
LEFT JOIN ISYST900 I WITH (NOLOCK) ON SR.ESTADORENUNCIA=I.TBLCODARG
WHERE P.CIP IS NOT NULL AND P.CODIGOAGENCIA <>12 AND DS.SITUACION<>7 AND I.TBLCODTAB=35
AND P.dw_fechaCarga = CAST(GETDATE() - 1 AS DATE)


--SELECT * FROM ISYST900 where TBLCODTAB=35


--SELECT * FROM DW_SOLICITUDRENUNCIA


