--USE [DWCOOPAC]
--GO
--/****** Object:  StoredProcedure [dbo].[usp_wt_activosretiradosagencia]    Script Date: 26/10/2023 17:06:33 ******/
--SET ANSI_NULLS ON
--GO
--SET QUOTED_IDENTIFIER ON
--GO

--ALTER procedure [dbo].[usp_wt_activosretiradosagencia]
--as
--set nocount on --
--set xact_abort on
--	begin transaction
--	begin try

-- Elimina la tabla temporal si existe
DROP TABLE IF EXISTS #DW_PERSONA_SOCIO;

---- Datos de personas
--SELECT DISTINCT
--    P.CIP,
--    P.NOMBRECOMPLETO AS NOMBRE,
--    P.TIPOPERSONADESCRI,
--    P.TIPOPERSONA,
--    P.SEXO,
--    P.EDAD,
--    P.CODIGOUSUARIO AS CODIGOUSUARIOPER,
--    P.ESTADOCIVILDESCRI,
--    P.NUMERODOCUMENTOID,
--    P.TIPODOCUMENTODESCRI,
--    P.FECHAINGRESOCOOP,
--	CONVERT(VARCHAR(7), NULL) AS CODIGOPERSONA,
--	CONVERT(INT, NULL) AS SITUACIONORIGEN,
--	CONVERT(VARCHAR(50), NULL) AS AGENCIADESCRI,
--	CONVERT(DATE, NULL) AS FECHAAPROBACIONREN,
--    CONVERT(VARCHAR(15), NULL) AS USUARIORENUNCIA,
--    'SOLICITADO' AS ESTADO
--INTO #DW_PERSONA_SOCIO
--FROM DW_PERSONA P WITH (NOLOCK)
--LEFT JOIN DW_DATOSSOCIO DS WITH (NOLOCK) ON P.CODIGOPERSONA = DS.CODIGOPERSONA AND P.dw_fechaCarga = ds.dw_fechaCarga
--WHERE DS.CODIGOPERSONA IS NULL

--UNION

-- Datos de socios activos
SELECT DISTINCT
    P.CIP,
    P.NOMBRECOMPLETO AS NOMBRE,
    P.TIPOPERSONADESCRI,
    P.TIPOPERSONA,
    P.SEXO,
    P.EDAD,
    P.CODIGOUSUARIO AS CODIGOUSUARIOPER,
    P.ESTADOCIVILDESCRI,
    P.NUMERODOCUMENTOID,
    P.TIPODOCUMENTODESCRI,
    P.FECHAINGRESOCOOP,
    DS.CODIGOPERSONA,
    DS.SITUACIONORIGEN,
    DS.AGENCIADESCRI,
    CONVERT(DATE, NULL) AS FECHAAPROBACIONREN,
    CONVERT(VARCHAR(15), NULL) AS USUARIORENUNCIA,
    'ACTIVO' AS ESTADO
INTO #DW_PERSONA_SOCIO
FROM DW_DATOSSOCIO DS WITH (NOLOCK)
LEFT JOIN DW_PERSONA P WITH (NOLOCK) ON P.CODIGOPERSONA = DS.CODIGOPERSONA AND P.dw_fechaCarga = ds.dw_fechaCarga
WHERE P.FECHAINGRESOCOOP >= '2022-01-01'
AND DS.SITUACION NOT IN (2, 7)
AND P.dw_fechaCarga = CAST(GETDATE() - 1 AS DATE)

UNION

-- Datos de socios retirados
SELECT DISTINCT
    P.CIP,
    P.NOMBRECOMPLETO AS NOMBRE,
    P.TIPOPERSONADESCRI,
    P.TIPOPERSONA,
    P.SEXO,
    P.EDAD,
    P.CODIGOUSUARIO AS CODIGOUSUARIOPER,
    P.ESTADOCIVILDESCRI,
    P.NUMERODOCUMENTOID,
    P.TIPODOCUMENTODESCRI,
    P.FECHAINGRESOCOOP,
    DS.CODIGOPERSONA,
    DS.SITUACIONORIGEN,
    DS.AGENCIADESCRI,
    SR.FECHAAPROBACION AS FECHAAPROBACIONREN,
    SR.CODIGOUSUARIO AS USUARIORENUNCIA,
    'RETIRADO' AS ESTADO
FROM DW_DATOSSOCIO DS WITH (NOLOCK)
INNER JOIN DW_SOLICITUDRENUNCIA SR WITH (NOLOCK) ON SR.CODIGOPERSONA = DS.CODIGOPERSONA
LEFT JOIN DW_PERSONA P WITH (NOLOCK) ON P.CODIGOPERSONA = DS.CODIGOPERSONA AND P.dw_fechaCarga = ds.dw_fechaCarga
WHERE SR.FECHAAPROBACION >= '2022-01-01'
AND SR.ESTADORENUNCIA IN (2, 4)
AND DS.SITUACION = 3
AND P.dw_fechaCarga = CAST(GETDATE() - 1 AS DATE)
AND P.CIP IS NOT NULL
AND P.SITUACION = 3;


-- Elimina la tabla temporal si existe
DROP TABLE IF EXISTS WT_ACTRETAGENCIA

SELECT DISTINCT

    NOMBRE,
	CIP,
    agenciadescri AS AGENCIA,
    CONVERT(DATE, FECHAINGRESOCOOP) AS FECHAINGRESO,
    FECHAAPROBACIONREN AS FECHARETIRO,
    DATEDIFF(DAY, FECHAINGRESOCOOP, ISNULL(FECHAAPROBACIONREN, CONVERT(DATE, GETDATE() - 1))) AS DIASDURACION,
    TIPOPERSONADESCRI AS TIPOPERSONA,
    SEXO,
    CODIGOUSUARIOPER AS USUARIO,
    EDAD,
    ESTADOCIVILDESCRI AS ESTADOCIVIL,
    TIPODOCUMENTODESCRI AS TIPODOCUMENTO,
    NUMERODOCUMENTOID AS NUMERODOCUMENTO,
    ESTADO AS ESTADOCIP,
    IIF(ESTADO = 'ACTIVO', 1, 0) AS FLAGSOCIOACTIVO,
    IIF(ESTADO = 'RETIRADO', 1, 0) AS FLAGSOCIOINACTIVO
    --IIF(ESTADO = 'SOLICITADO', 1, 0) AS [FLAG PERSONA]
INTO WT_ACTRETAGENCIA
FROM #DW_PERSONA_SOCIO

--SELECT 
--MONTH(FECHAINGRESO), COUNT(*)
--FROM #VW_REPORTE 
--WHERE YEAR(FECHAINGRESO)=2023 AND MONTH(FECHAINGRESO)>=9 AND CONVERT(DATE,FECHAINGRESO)<'2023-10-25'
--GROUP BY  MONTH(FECHAINGRESO)


--SELECT FECHAINGRESO,COUNT(*) FROM #VW_REPORTE 
--WHERE  CONVERT(DATE,FECHAINGRESO)>='2023-10-01' AND ESTADOCIP<>'SOLICITADO'
--GROUP BY FECHAINGRESO 
--ORDER BY FECHAINGRESO ASC


-- Limpiar las tablas temporales 
 
