----Obtener nombre de las tablas -------------------------------
SELECT UPPER(table_name)TABLE_NAME,
TIPO= UPPER(LEFT(table_name,2))
FROM information_schema.tables 
WHERE table_schema = 'dbo'
and TABLE_CATALOG='DWCOOPAC' AND TABLE_TYPE='BASE TABLE'
and LEFT(table_name,2) in ('WT','DW')



-----Unir tablas con las fechas 
DECLARE @FECHA DATE = (SELECT FECHA FROM ST_FECHAMAESTRA WHERE ESTADO = 1)

DROP TABLE IF EXISTS #FECHA
SELECT  
FECHA,
FINMES,
MESACTUAL=IIF(FORMAT(FECHA,'yyyyMM')=FORMAT(@FECHA,'yyyyMM'),'SI','NO')
INTO #FECHA
FROM ST_CALENDARIO WHERE FECHA<=@FECHA


SELECT * FROM #FECHA



DROP TABLE IF EXISTS #DW_AGENCIAOPERACIONES
SELECT 
FECHAUSUARIO, 
COUNT (*) CONTEO,
'CIERRE MES'FRECUENCIA
INTO #DW_AGENCIAOPERACIONES 
FROM DW_AGENCIAOPERACIONES
GROUP BY FECHAUSUARIO
ORDER BY FECHAUSUARIO DESC


SELECT 
A.FECHA,
A.FINMES,
A.MESACTUAL,
B.CONTEO,
B.FRECUENCIA
FROM 
#FECHA A
LEFT JOIN #DW_AGENCIAOPERACIONES B ON A.Fecha=B.FECHAUSUARIO
WHERE A.FinMes='SI' OR MESACTUAL='SI'


SELECT * FROM DW_AGENCIAOPERACIONES
WHERE FECHAUSUARIO='2023-12-31' 