USE [DWCOOPAC]
GO

INSERT INTO ST_INDICADORES_PASSWORD
Select 'Melissa Lozada'[Usuario], '12345678'[Contraseña] 

DROP TABLE ST_INDICADORES_PASSWORD
CREATE TABLE ST_INDICADORES_PASSWORD (
    ID INT PRIMARY KEY IDENTITY(1,1),
    Usuario NVARCHAR(50),
    Contraseña  NVARCHAR(50)
);




CREATE TABLE ST_FECHA_VALIDADA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    Usuario NVARCHAR(50),
    Fecha DATE,
    FechaRegistro DATETIME
);


delete FROM ST_FECHA_VALIDADA where id=2

INSERT ST_FECHA_VALIDADA VALUES('Prueba',convert(Date,'2023-12-12 00:00:00'),GETDATE())

EXEC [dbo].[usp_dash_calendario]

SELECT * FROM ST_INDICADORES_PASSWORD
SELECT * FROM ST_FECHA_VALIDADA